//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FavoImgs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FavoImgs.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already downloaded. skip....
        /// </summary>
        internal static string AlreadyDownloaded {
            get {
                return ResourceManager.GetString("AlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API rate limit exceeded. Try again after 60 seconds....
        /// </summary>
        internal static string APIRateLimitExceeded {
            get {
                return ResourceManager.GetString("APIRateLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create download folder!.
        /// </summary>
        internal static string CannotCreateDownloadFolder {
            get {
                return ResourceManager.GetString("CannotCreateDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read OAuth Token!.
        /// </summary>
        internal static string CannotReadOAuthToken {
            get {
                return ResourceManager.GetString("CannotReadOAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Path.
        /// </summary>
        internal static string DownloadPath {
            get {
                return ResourceManager.GetString("DownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get tweet(s) from Twitter....
        /// </summary>
        internal static string GetTweetsFromTwitter {
            get {
                return ResourceManager.GetString("GetTweetsFromTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset saved download path..
        /// </summary>
        internal static string ResetDownloadPath {
            get {
                return ResourceManager.GetString("ResetDownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder to save....
        /// </summary>
        internal static string SelectFolderToSave {
            get {
                return ResourceManager.GetString("SelectFolderToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again....
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work complete!.
        /// </summary>
        internal static string WorkComplete {
            get {
                return ResourceManager.GetString("WorkComplete", resourceCulture);
            }
        }
    }
}
